### ISSUE TITLE
Failed to process keys with hyphens

### ISSUE THREAD

**Issue by abdullahezzat1** [rexxars/sanity-diff-patch#28]
Hello, team.

I'm getting the following error while using `diffPatch()`:

```
    err: {
      "type": "DiffError",
      "message": "Keys can only contain letters, numbers and underscores (at 'products[0].comparisonFields.support-level')",
      "stack":
          Error: Keys can only contain letters, numbers and underscores (at 'products[0].comparisonFields.support-level')
              at validateProperty (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/validate.ts:52:11)
              at map (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:271:19)
              at Array.map (<anonymous>)
              at diffObject (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:271:6)
              at diffItem (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:258:7)
              at diffObject (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:291:5)
              at diffItem (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:258:7)
              at diffArrayByIndex (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:360:5)
              at diffArray (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:349:7)
              at diffItem (/media/Main/puma/sanity-studio-cms/node_modules/sanity-diff-patch/src/diffPatch.ts:257:7)
      "path": [
        "products",
        0,
        "comparisonFields",
        "support-level"
      ],
      "serializedPath": "products[0].comparisonFields.support-level",
      "value": "Neutral Support"
    }

```

The function should be able to handle paths like this `products[0].comparisonFields["support-level"]`

Thank you in advance.

**Comment by rexxars** [comment]
Thanks for reporting! Fixed in [v3.0.4](https://github.com/rexxars/sanity-diff-patch/releases/tag/v3.0.4) - note that using dashes is generally discouraged if you're using the Sanity Studio
